name: Unit Test

on: [push,pull_request]

jobs:
  run-test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go env
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: run unit test
        run:  go test -race -coverprofile=coverage -covermode=atomic -v ./...
      - name: upload code coverage
        uses: codecov/codecov-action@v3
